source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!


target 'MarvelApp' do
    pod 'CryptoSwift'
    pod 'AlamofireImage', '~> 3.4'
end

target 'MarvelAppTests' do
    pod 'CryptoSwift'
    pod 'AlamofireImage', '~> 3.4'
end


